using DiamondKataSolver;

namespace DiamondKataSolverTests;

public sealed class DiamondTests
{
    [Fact]
    public void Given_A_CreateDiamond_Returns_Expected_Output()
    {
        // Arrange
        Diamond diamond = new Diamond();
        
        // Act/Assert
        Assert.Equal("A", diamond.CreateDiamond('A'));
    }

    [Theory]
    [MemberData(nameof(GetTestData))]
    public void Given_Valid_Letter_CreateDiamond_Returns_Correct_Diamond_Sequence(char girdleLetter, string expectedOutput)
    {
        // Arrange
        Diamond diamond = new Diamond();

        // Act/Assert
        Assert.Equal(expectedOutput, diamond.CreateDiamond(girdleLetter));
    }

    public static IEnumerable<object[]> GetTestData()
    {
        return new List<object[]>
        {
            new object[] { 'a', "a" },
            new object[] { 'A', "A" },
            new object[] { 'b', " a\nb b\n a\n" },
            new object[] { 'B', " A\nB B\n A\n" },
            new object[] { 'c', "  a\n b b\nc   c\n b b\n  a\n" },
            new object[] { 'C', "  A\n B B\nC   C\n B B\n  A\n" },
            new object[] { 'd', "   a\n  b b\n c   c\nd     d\n c   c\n  b b\n   a\n" },
            new object[] { 'D', "   A\n  B B\n C   C\nD     D\n C   C\n  B B\n   A\n" },
            new object[] { 'e', "    a\n   b b\n  c   c\n d     d\ne       e\n d     d\n  c   c\n   b b\n    a\n" },
            new object[] { 'E', "    A\n   B B\n  C   C\n D     D\nE       E\n D     D\n  C   C\n   B B\n    A\n" },
            new object[] { 'f', "     a\n    b b\n   c   c\n  d     d\n e       e\nf         f\n e       e\n  d     d\n   c   c\n    b b\n     a\n" },
            new object[] { 'F', "     A\n    B B\n   C   C\n  D     D\n E       E\nF         F\n E       E\n  D     D\n   C   C\n    B B\n     A\n" },
            new object[] { 'g', "      a\n     b b\n    c   c\n   d     d\n  e       e\n f         f\ng           g\n f         f\n  e       e\n   d     d\n    c   c\n     b b\n      a\n" },
            new object[] { 'G', "      A\n     B B\n    C   C\n   D     D\n  E       E\n F         F\nG           G\n F         F\n  E       E\n   D     D\n    C   C\n     B B\n      A\n" },
            new object[] { 'h', "       a\n      b b\n     c   c\n    d     d\n   e       e\n  f         f\n g           g\nh             h\n g           g\n  f         f\n   e       e\n    d     d\n     c   c\n      b b\n       a\n" },
            new object[] { 'H', "       A\n      B B\n     C   C\n    D     D\n   E       E\n  F         F\n G           G\nH             H\n G           G\n  F         F\n   E       E\n    D     D\n     C   C\n      B B\n       A\n" },
            new object[] { 'i', "        a\n       b b\n      c   c\n     d     d\n    e       e\n   f         f\n  g           g\n h             h\ni               i\n h             h\n  g           g\n   f         f\n    e       e\n     d     d\n      c   c\n       b b\n        a\n" },
            new object[] { 'I', "        A\n       B B\n      C   C\n     D     D\n    E       E\n   F         F\n  G           G\n H             H\nI               I\n H             H\n  G           G\n   F         F\n    E       E\n     D     D\n      C   C\n       B B\n        A\n" },
            new object[] { 'j', "         a\n        b b\n       c   c\n      d     d\n     e       e\n    f         f\n   g           g\n  h             h\n i               i\nj                 j\n i               i\n  h             h\n   g           g\n    f         f\n     e       e\n      d     d\n       c   c\n        b b\n         a\n" },
            new object[] { 'J', "         A\n        B B\n       C   C\n      D     D\n     E       E\n    F         F\n   G           G\n  H             H\n I               I\nJ                 J\n I               I\n  H             H\n   G           G\n    F         F\n     E       E\n      D     D\n       C   C\n        B B\n         A\n" },
            new object[] { 'k', "          a\n         b b\n        c   c\n       d     d\n      e       e\n     f         f\n    g           g\n   h             h\n  i               i\n j                 j\nk                   k\n j                 j\n  i               i\n   h             h\n    g           g\n     f         f\n      e       e\n       d     d\n        c   c\n         b b\n          a\n" },
            new object[] { 'K', "          A\n         B B\n        C   C\n       D     D\n      E       E\n     F         F\n    G           G\n   H             H\n  I               I\n J                 J\nK                   K\n J                 J\n  I               I\n   H             H\n    G           G\n     F         F\n      E       E\n       D     D\n        C   C\n         B B\n          A\n" },
            new object[] { 'l', "           a\n          b b\n         c   c\n        d     d\n       e       e\n      f         f\n     g           g\n    h             h\n   i               i\n  j                 j\n k                   k\nl                     l\n k                   k\n  j                 j\n   i               i\n    h             h\n     g           g\n      f         f\n       e       e\n        d     d\n         c   c\n          b b\n           a\n" },
            new object[] { 'L', "           A\n          B B\n         C   C\n        D     D\n       E       E\n      F         F\n     G           G\n    H             H\n   I               I\n  J                 J\n K                   K\nL                     L\n K                   K\n  J                 J\n   I               I\n    H             H\n     G           G\n      F         F\n       E       E\n        D     D\n         C   C\n          B B\n           A\n" },
            new object[] { 'm', "            a\n           b b\n          c   c\n         d     d\n        e       e\n       f         f\n      g           g\n     h             h\n    i               i\n   j                 j\n  k                   k\n l                     l\nm                       m\n l                     l\n  k                   k\n   j                 j\n    i               i\n     h             h\n      g           g\n       f         f\n        e       e\n         d     d\n          c   c\n           b b\n            a\n" },
            new object[] { 'M', "            A\n           B B\n          C   C\n         D     D\n        E       E\n       F         F\n      G           G\n     H             H\n    I               I\n   J                 J\n  K                   K\n L                     L\nM                       M\n L                     L\n  K                   K\n   J                 J\n    I               I\n     H             H\n      G           G\n       F         F\n        E       E\n         D     D\n          C   C\n           B B\n            A\n" },
            new object[] { 'n', "             a\n            b b\n           c   c\n          d     d\n         e       e\n        f         f\n       g           g\n      h             h\n     i               i\n    j                 j\n   k                   k\n  l                     l\n m                       m\nn                         n\n m                       m\n  l                     l\n   k                   k\n    j                 j\n     i               i\n      h             h\n       g           g\n        f         f\n         e       e\n          d     d\n           c   c\n            b b\n             a\n" },
            new object[] { 'N', "             A\n            B B\n           C   C\n          D     D\n         E       E\n        F         F\n       G           G\n      H             H\n     I               I\n    J                 J\n   K                   K\n  L                     L\n M                       M\nN                         N\n M                       M\n  L                     L\n   K                   K\n    J                 J\n     I               I\n      H             H\n       G           G\n        F         F\n         E       E\n          D     D\n           C   C\n            B B\n             A\n" },
            new object[] { 'o', "              a\n             b b\n            c   c\n           d     d\n          e       e\n         f         f\n        g           g\n       h             h\n      i               i\n     j                 j\n    k                   k\n   l                     l\n  m                       m\n n                         n\no                           o\n n                         n\n  m                       m\n   l                     l\n    k                   k\n     j                 j\n      i               i\n       h             h\n        g           g\n         f         f\n          e       e\n           d     d\n            c   c\n             b b\n              a\n" },
            new object[] { 'O', "              A\n             B B\n            C   C\n           D     D\n          E       E\n         F         F\n        G           G\n       H             H\n      I               I\n     J                 J\n    K                   K\n   L                     L\n  M                       M\n N                         N\nO                           O\n N                         N\n  M                       M\n   L                     L\n    K                   K\n     J                 J\n      I               I\n       H             H\n        G           G\n         F         F\n          E       E\n           D     D\n            C   C\n             B B\n              A\n" },
            new object[] { 'p', "               a\n              b b\n             c   c\n            d     d\n           e       e\n          f         f\n         g           g\n        h             h\n       i               i\n      j                 j\n     k                   k\n    l                     l\n   m                       m\n  n                         n\n o                           o\np                             p\n o                           o\n  n                         n\n   m                       m\n    l                     l\n     k                   k\n      j                 j\n       i               i\n        h             h\n         g           g\n          f         f\n           e       e\n            d     d\n             c   c\n              b b\n               a\n" },
            new object[] { 'P', "               A\n              B B\n             C   C\n            D     D\n           E       E\n          F         F\n         G           G\n        H             H\n       I               I\n      J                 J\n     K                   K\n    L                     L\n   M                       M\n  N                         N\n O                           O\nP                             P\n O                           O\n  N                         N\n   M                       M\n    L                     L\n     K                   K\n      J                 J\n       I               I\n        H             H\n         G           G\n          F         F\n           E       E\n            D     D\n             C   C\n              B B\n               A\n" },
            new object[] { 'q', "                a\n               b b\n              c   c\n             d     d\n            e       e\n           f         f\n          g           g\n         h             h\n        i               i\n       j                 j\n      k                   k\n     l                     l\n    m                       m\n   n                         n\n  o                           o\n p                             p\nq                               q\n p                             p\n  o                           o\n   n                         n\n    m                       m\n     l                     l\n      k                   k\n       j                 j\n        i               i\n         h             h\n          g           g\n           f         f\n            e       e\n             d     d\n              c   c\n               b b\n                a\n" },
            new object[] { 'Q', "                A\n               B B\n              C   C\n             D     D\n            E       E\n           F         F\n          G           G\n         H             H\n        I               I\n       J                 J\n      K                   K\n     L                     L\n    M                       M\n   N                         N\n  O                           O\n P                             P\nQ                               Q\n P                             P\n  O                           O\n   N                         N\n    M                       M\n     L                     L\n      K                   K\n       J                 J\n        I               I\n         H             H\n          G           G\n           F         F\n            E       E\n             D     D\n              C   C\n               B B\n                A\n" },
            new object[] { 'r', "                 a\n                b b\n               c   c\n              d     d\n             e       e\n            f         f\n           g           g\n          h             h\n         i               i\n        j                 j\n       k                   k\n      l                     l\n     m                       m\n    n                         n\n   o                           o\n  p                             p\n q                               q\nr                                 r\n q                               q\n  p                             p\n   o                           o\n    n                         n\n     m                       m\n      l                     l\n       k                   k\n        j                 j\n         i               i\n          h             h\n           g           g\n            f         f\n             e       e\n              d     d\n               c   c\n                b b\n                 a\n" },
            new object[] { 'R', "                 A\n                B B\n               C   C\n              D     D\n             E       E\n            F         F\n           G           G\n          H             H\n         I               I\n        J                 J\n       K                   K\n      L                     L\n     M                       M\n    N                         N\n   O                           O\n  P                             P\n Q                               Q\nR                                 R\n Q                               Q\n  P                             P\n   O                           O\n    N                         N\n     M                       M\n      L                     L\n       K                   K\n        J                 J\n         I               I\n          H             H\n           G           G\n            F         F\n             E       E\n              D     D\n               C   C\n                B B\n                 A\n" },
            new object[] { 's', "                  a\n                 b b\n                c   c\n               d     d\n              e       e\n             f         f\n            g           g\n           h             h\n          i               i\n         j                 j\n        k                   k\n       l                     l\n      m                       m\n     n                         n\n    o                           o\n   p                             p\n  q                               q\n r                                 r\ns                                   s\n r                                 r\n  q                               q\n   p                             p\n    o                           o\n     n                         n\n      m                       m\n       l                     l\n        k                   k\n         j                 j\n          i               i\n           h             h\n            g           g\n             f         f\n              e       e\n               d     d\n                c   c\n                 b b\n                  a\n" },
            new object[] { 'S', "                  A\n                 B B\n                C   C\n               D     D\n              E       E\n             F         F\n            G           G\n           H             H\n          I               I\n         J                 J\n        K                   K\n       L                     L\n      M                       M\n     N                         N\n    O                           O\n   P                             P\n  Q                               Q\n R                                 R\nS                                   S\n R                                 R\n  Q                               Q\n   P                             P\n    O                           O\n     N                         N\n      M                       M\n       L                     L\n        K                   K\n         J                 J\n          I               I\n           H             H\n            G           G\n             F         F\n              E       E\n               D     D\n                C   C\n                 B B\n                  A\n" },
            new object[] { 't', "                   a\n                  b b\n                 c   c\n                d     d\n               e       e\n              f         f\n             g           g\n            h             h\n           i               i\n          j                 j\n         k                   k\n        l                     l\n       m                       m\n      n                         n\n     o                           o\n    p                             p\n   q                               q\n  r                                 r\n s                                   s\nt                                     t\n s                                   s\n  r                                 r\n   q                               q\n    p                             p\n     o                           o\n      n                         n\n       m                       m\n        l                     l\n         k                   k\n          j                 j\n           i               i\n            h             h\n             g           g\n              f         f\n               e       e\n                d     d\n                 c   c\n                  b b\n                   a\n" },
            new object[] { 'T', "                   A\n                  B B\n                 C   C\n                D     D\n               E       E\n              F         F\n             G           G\n            H             H\n           I               I\n          J                 J\n         K                   K\n        L                     L\n       M                       M\n      N                         N\n     O                           O\n    P                             P\n   Q                               Q\n  R                                 R\n S                                   S\nT                                     T\n S                                   S\n  R                                 R\n   Q                               Q\n    P                             P\n     O                           O\n      N                         N\n       M                       M\n        L                     L\n         K                   K\n          J                 J\n           I               I\n            H             H\n             G           G\n              F         F\n               E       E\n                D     D\n                 C   C\n                  B B\n                   A\n" },
            new object[] { 'u', "                    a\n                   b b\n                  c   c\n                 d     d\n                e       e\n               f         f\n              g           g\n             h             h\n            i               i\n           j                 j\n          k                   k\n         l                     l\n        m                       m\n       n                         n\n      o                           o\n     p                             p\n    q                               q\n   r                                 r\n  s                                   s\n t                                     t\nu                                       u\n t                                     t\n  s                                   s\n   r                                 r\n    q                               q\n     p                             p\n      o                           o\n       n                         n\n        m                       m\n         l                     l\n          k                   k\n           j                 j\n            i               i\n             h             h\n              g           g\n               f         f\n                e       e\n                 d     d\n                  c   c\n                   b b\n                    a\n" },
            new object[] { 'U', "                    A\n                   B B\n                  C   C\n                 D     D\n                E       E\n               F         F\n              G           G\n             H             H\n            I               I\n           J                 J\n          K                   K\n         L                     L\n        M                       M\n       N                         N\n      O                           O\n     P                             P\n    Q                               Q\n   R                                 R\n  S                                   S\n T                                     T\nU                                       U\n T                                     T\n  S                                   S\n   R                                 R\n    Q                               Q\n     P                             P\n      O                           O\n       N                         N\n        M                       M\n         L                     L\n          K                   K\n           J                 J\n            I               I\n             H             H\n              G           G\n               F         F\n                E       E\n                 D     D\n                  C   C\n                   B B\n                    A\n" },
            new object[] { 'v', "                     a\n                    b b\n                   c   c\n                  d     d\n                 e       e\n                f         f\n               g           g\n              h             h\n             i               i\n            j                 j\n           k                   k\n          l                     l\n         m                       m\n        n                         n\n       o                           o\n      p                             p\n     q                               q\n    r                                 r\n   s                                   s\n  t                                     t\n u                                       u\nv                                         v\n u                                       u\n  t                                     t\n   s                                   s\n    r                                 r\n     q                               q\n      p                             p\n       o                           o\n        n                         n\n         m                       m\n          l                     l\n           k                   k\n            j                 j\n             i               i\n              h             h\n               g           g\n                f         f\n                 e       e\n                  d     d\n                   c   c\n                    b b\n                     a\n" },
            new object[] { 'V', "                     A\n                    B B\n                   C   C\n                  D     D\n                 E       E\n                F         F\n               G           G\n              H             H\n             I               I\n            J                 J\n           K                   K\n          L                     L\n         M                       M\n        N                         N\n       O                           O\n      P                             P\n     Q                               Q\n    R                                 R\n   S                                   S\n  T                                     T\n U                                       U\nV                                         V\n U                                       U\n  T                                     T\n   S                                   S\n    R                                 R\n     Q                               Q\n      P                             P\n       O                           O\n        N                         N\n         M                       M\n          L                     L\n           K                   K\n            J                 J\n             I               I\n              H             H\n               G           G\n                F         F\n                 E       E\n                  D     D\n                   C   C\n                    B B\n                     A\n" },
            new object[] { 'w', "                      a\n                     b b\n                    c   c\n                   d     d\n                  e       e\n                 f         f\n                g           g\n               h             h\n              i               i\n             j                 j\n            k                   k\n           l                     l\n          m                       m\n         n                         n\n        o                           o\n       p                             p\n      q                               q\n     r                                 r\n    s                                   s\n   t                                     t\n  u                                       u\n v                                         v\nw                                           w\n v                                         v\n  u                                       u\n   t                                     t\n    s                                   s\n     r                                 r\n      q                               q\n       p                             p\n        o                           o\n         n                         n\n          m                       m\n           l                     l\n            k                   k\n             j                 j\n              i               i\n               h             h\n                g           g\n                 f         f\n                  e       e\n                   d     d\n                    c   c\n                     b b\n                      a\n" },
            new object[] { 'W', "                      A\n                     B B\n                    C   C\n                   D     D\n                  E       E\n                 F         F\n                G           G\n               H             H\n              I               I\n             J                 J\n            K                   K\n           L                     L\n          M                       M\n         N                         N\n        O                           O\n       P                             P\n      Q                               Q\n     R                                 R\n    S                                   S\n   T                                     T\n  U                                       U\n V                                         V\nW                                           W\n V                                         V\n  U                                       U\n   T                                     T\n    S                                   S\n     R                                 R\n      Q                               Q\n       P                             P\n        O                           O\n         N                         N\n          M                       M\n           L                     L\n            K                   K\n             J                 J\n              I               I\n               H             H\n                G           G\n                 F         F\n                  E       E\n                   D     D\n                    C   C\n                     B B\n                      A\n" },
            new object[] { 'x', "                       a\n                      b b\n                     c   c\n                    d     d\n                   e       e\n                  f         f\n                 g           g\n                h             h\n               i               i\n              j                 j\n             k                   k\n            l                     l\n           m                       m\n          n                         n\n         o                           o\n        p                             p\n       q                               q\n      r                                 r\n     s                                   s\n    t                                     t\n   u                                       u\n  v                                         v\n w                                           w\nx                                             x\n w                                           w\n  v                                         v\n   u                                       u\n    t                                     t\n     s                                   s\n      r                                 r\n       q                               q\n        p                             p\n         o                           o\n          n                         n\n           m                       m\n            l                     l\n             k                   k\n              j                 j\n               i               i\n                h             h\n                 g           g\n                  f         f\n                   e       e\n                    d     d\n                     c   c\n                      b b\n                       a\n" },
            new object[] { 'X', "                       A\n                      B B\n                     C   C\n                    D     D\n                   E       E\n                  F         F\n                 G           G\n                H             H\n               I               I\n              J                 J\n             K                   K\n            L                     L\n           M                       M\n          N                         N\n         O                           O\n        P                             P\n       Q                               Q\n      R                                 R\n     S                                   S\n    T                                     T\n   U                                       U\n  V                                         V\n W                                           W\nX                                             X\n W                                           W\n  V                                         V\n   U                                       U\n    T                                     T\n     S                                   S\n      R                                 R\n       Q                               Q\n        P                             P\n         O                           O\n          N                         N\n           M                       M\n            L                     L\n             K                   K\n              J                 J\n               I               I\n                H             H\n                 G           G\n                  F         F\n                   E       E\n                    D     D\n                     C   C\n                      B B\n                       A\n" },
            new object[] { 'y', "                        a\n                       b b\n                      c   c\n                     d     d\n                    e       e\n                   f         f\n                  g           g\n                 h             h\n                i               i\n               j                 j\n              k                   k\n             l                     l\n            m                       m\n           n                         n\n          o                           o\n         p                             p\n        q                               q\n       r                                 r\n      s                                   s\n     t                                     t\n    u                                       u\n   v                                         v\n  w                                           w\n x                                             x\ny                                               y\n x                                             x\n  w                                           w\n   v                                         v\n    u                                       u\n     t                                     t\n      s                                   s\n       r                                 r\n        q                               q\n         p                             p\n          o                           o\n           n                         n\n            m                       m\n             l                     l\n              k                   k\n               j                 j\n                i               i\n                 h             h\n                  g           g\n                   f         f\n                    e       e\n                     d     d\n                      c   c\n                       b b\n                        a\n" },
            new object[] { 'Y', "                        A\n                       B B\n                      C   C\n                     D     D\n                    E       E\n                   F         F\n                  G           G\n                 H             H\n                I               I\n               J                 J\n              K                   K\n             L                     L\n            M                       M\n           N                         N\n          O                           O\n         P                             P\n        Q                               Q\n       R                                 R\n      S                                   S\n     T                                     T\n    U                                       U\n   V                                         V\n  W                                           W\n X                                             X\nY                                               Y\n X                                             X\n  W                                           W\n   V                                         V\n    U                                       U\n     T                                     T\n      S                                   S\n       R                                 R\n        Q                               Q\n         P                             P\n          O                           O\n           N                         N\n            M                       M\n             L                     L\n              K                   K\n               J                 J\n                I               I\n                 H             H\n                  G           G\n                   F         F\n                    E       E\n                     D     D\n                      C   C\n                       B B\n                        A\n" },
            new object[] { 'z', "                         a\n                        b b\n                       c   c\n                      d     d\n                     e       e\n                    f         f\n                   g           g\n                  h             h\n                 i               i\n                j                 j\n               k                   k\n              l                     l\n             m                       m\n            n                         n\n           o                           o\n          p                             p\n         q                               q\n        r                                 r\n       s                                   s\n      t                                     t\n     u                                       u\n    v                                         v\n   w                                           w\n  x                                             x\n y                                               y\nz                                                 z\n y                                               y\n  x                                             x\n   w                                           w\n    v                                         v\n     u                                       u\n      t                                     t\n       s                                   s\n        r                                 r\n         q                               q\n          p                             p\n           o                           o\n            n                         n\n             m                       m\n              l                     l\n               k                   k\n                j                 j\n                 i               i\n                  h             h\n                   g           g\n                    f         f\n                     e       e\n                      d     d\n                       c   c\n                        b b\n                         a\n" },
            new object[] { 'Z', "                         A\n                        B B\n                       C   C\n                      D     D\n                     E       E\n                    F         F\n                   G           G\n                  H             H\n                 I               I\n                J                 J\n               K                   K\n              L                     L\n             M                       M\n            N                         N\n           O                           O\n          P                             P\n         Q                               Q\n        R                                 R\n       S                                   S\n      T                                     T\n     U                                       U\n    V                                         V\n   W                                           W\n  X                                             X\n Y                                               Y\nZ                                                 Z\n Y                                               Y\n  X                                             X\n   W                                           W\n    V                                         V\n     U                                       U\n      T                                     T\n       S                                   S\n        R                                 R\n         Q                               Q\n          P                             P\n           O                           O\n            N                         N\n             M                       M\n              L                     L\n               K                   K\n                J                 J\n                 I               I\n                  H             H\n                   G           G\n                    F         F\n                     E       E\n                      D     D\n                       C   C\n                        B B\n                         A\n" }
        };
    }
}
